config/routes.rb
Rails.application.routes.draw do
  resources :sequences, except: [:destroy, :edit, :update]
  resources :settings
  resources :loans
  resources :books do
    get 'clone', on: :collection
  end
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#logout'
  root 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  include Mongoid::Timestamps

  field :name, type: String
  field :email, type: String
  field :password_digest, type: String

  has_secure_password

  paginates_per 1 if Rails.env.development?

  index({ email: 1 }, { unique: true })
  validates_length_of :password, minimum: 8
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order_by([:name, :asc]).page(params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Modifica Utente</h1>

<%= render 'form', user: @user %>
<br />
<div class="btn-group" role="group" aria-label="Strumenti">
    <%= link_to 'Visualizza', @user, class: "btn btn-primary" %>
    <%= link_to 'Utenti', users_path, class: "btn btn-primary" %>
</div>

app/views/users/index.html.erb
<h1>Utenti</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= t('mongoid.attributes.user.name') %></th>
      <th>Email</th>
      <th colspan="3" class="text-center"><span class="bi bi-tools"></span></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to user, title: "Visualizza" do %>
            <span class="bi bi-view-list"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_user_path(user), title: "Modifica" do %>
            <span class="bi bi-pencil-square"></span>
          <% end %>
        </td>
        <td>
          <%= link_to user, method: :delete, data: { confirm: 'Sei sicuro?' }, title: "Cancella" do %>
            <span class="bi bi-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

<div class="btn-group" role="group" aria-label="Strumenti">
  <%= link_to 'Nuovo Utente', new_user_path, class: "btn btn-primary" %>
  <%= link_to 'Home', welcome_path, class: "btn btn-primary" %>
</div>

app/views/users/new.html.erb
<h1>Nuovo Utente</h1>

<%= render 'form', user: @user %>
<br />
<div class="btn-group" role="group" aria-label="Strumenti">
    <%= link_to 'Utenti', users_path, class: "btn btn-primary" %>
</div>

app/views/users/show.html.erb
<p>
  <strong><%= t('mongoid.attributes.user.name') %>:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<div class="btn-group" role="group" aria-label="Strumenti">
  <%= link_to 'Modifica', edit_user_path(@user), class: "btn btn-primary" %>
  <%= link_to 'Utenti', users_path, class: "btn btn-primary" %>
</div>