config/routes.rb
Rails.application.routes.draw do
  resources :sequences, except: [:destroy, :edit, :update]
  resources :settings
  resources :loans
  resources :books do
    get 'clone', on: :collection
  end
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#logout'
  root 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
class Setting
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  field :key, type: String
  field :value, type: String
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authorized
  before_action :set_setting, only: %i[ show edit update destroy ]

  # GET /settings or /settings.json
  def index
    @settings = Setting.page(params[:page]).all
  end

  # GET /settings/1 or /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings or /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: "Setting was successfully created." }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1 or /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: "Setting was successfully updated." }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1 or /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: "Setting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setting_params
      params.require(:setting).permit(:key, :value)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper

    def day_of_quarantine_in_setting
        day_of_quarantine_in_setting = Setting.where(key: "quarantine").first
        day_of_quarantine = day_of_quarantine_in_setting ? day_of_quarantine_in_setting.value.to_i + 1 : 10
    end

    def day_of_expected_return_in_setting
        day_of_expected_return_in_setting = Setting.where(key: "expected_return").first
        day_of_expected_return = day_of_expected_return_in_setting ? day_of_expected_return_in_setting.value.to_i.days + 1 : 1.month
    end
end

app/views/settings/_form.html.erb
<%= form_with(model: setting, local: true) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
        <% setting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :key %>
    <%= form.text_field :key, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :value %>
    <%= form.text_field :value, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<br />
<div class="btn-group" role="group" aria-label="Strumenti">
    <%= link_to 'Visualizza', @setting, class: "btn btn-primary" %>
    <%= link_to 'Impostazioni', settings_path, class: "btn btn-primary" %>
</div>

app/views/settings/index.html.erb
<h1><%= t('mongoid.models.setting.other') %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Key</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.key %></td>
        <td><%= setting.value %></td>
        <td>
          <%= link_to setting, title: "Visualizza" do %>
            <span class="bi bi-view-list"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_setting_path(setting), title: "Modifica" do %>
            <span class="bi bi-pencil-square"></span>
          <% end %>
        </td>
        <td>
          <%= link_to setting, method: :delete, data: { confirm: 'Sei sicuro?' }, title: "Cancella" do %>
            <span class="bi bi-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @settings %>

<div class="btn-group" role="group" aria-label="Strumenti">
  <%= link_to 'Nuova Impostazione', new_setting_path, class: "btn btn-primary" %>
  <%= link_to 'Home', welcome_path, class: "btn btn-primary" %>
</div>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<br />
<div class="btn-group" role="group" aria-label="Strumenti">
    <%= link_to 'Impostazioni', settings_path, class: "btn btn-primary" %>
</div>

app/views/settings/show.html.erb
<p>
  <strong>Key:</strong>
  <%= @setting.key %>
</p>

<p>
  <strong>Value:</strong>
  <%= @setting.value %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>