config/routes.rb
Rails.application.routes.draw do
  resources :sequences, except: [:destroy, :edit, :update]
  resources :settings
  resources :loans
  resources :books do
    get 'clone', on: :collection
  end
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#logout'
  root 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :authors, type: Array
  field :year, type: Integer
  field :genre, type: String
  field :language, type: String
  field :spot, type: String
  field :isbn, type: String
  field :abstract, type: String
  field :code, type: Integer
  field :catalogue, type: String

  has_many :loans

  paginates_per 2 if Rails.env.development?

  index({ code: 1 }, { unique: true, language_override: "lang", default_language: "it" })
  index({ year: 1 }, { unique: false, language_override: "lang", default_language: "it" })
  index({ "$**": "text" }, { language_override: "lang", default_language: "it" })

  validates :code, uniqueness: { case_sensitive: false }
  validates_presence_of :code
  validates_presence_of :title
  validates_presence_of :authors
  validates_presence_of :spot
  validates_presence_of :isbn

  scope :late, -> (day) { Book.where({ id: { "$in" => Loan.late(day).pluck(:book_id).uniq }})}

  scope :max_code, -> () { Book.order_by({ code: :desc }).limit(1) }

  def self.next_code
    value = nil
    key = self.name
    if Sequence.max_sequence(key).first.nil?
      book = max_code.first
      value = book.nil? ? 1 : book.code + 1
    end
    sequence = Sequence.create_sequence(key, value)
    sequence.value
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authorized, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
    @books = @books.any_of({ '$text' => { '$search' => params[:q] }}, { code: params[:q] }, { year:  params[:q] }) if !params[:q].blank?
    @books = @books.page(params[:page])
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/clone
  def clone
    @book = Book.new(book_params)
    @book.authors = params[:authors].split(',\s?')
    render :new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.code = Book.next_code
    @book.authors = params[:authors].split(',\s?')

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      @book.authors = params[:authors].split(',\s?')
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :year, :genre, :language, :spot, :isbn, :abstract, :catalogue)
    end
end

app/helpers/books_helper.rb
module BooksHelper
    def params_for_cloning(book)
        {
            book: {
                title: book.title,
                year: book.year,
                genre: book.genre,
                language: book.language,
                spot: book.spot,
                abstract: book.abstract,
                catalogue: book.catalogue
            },
            authors: book.authors
        }
    end
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% if book.persisted? %>
  <div class="form-group">
    <%= form.label :code %>
    <%= form.text_field :code, class: "form-control-plaintext", disabled: true %>
  </div>
<% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :authors %>
    <%= text_field_tag :authors, (book.authors.join(",") if book.authors), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :language %>
    <%= form.text_field :language, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :spot %>
    <%= form.text_field :spot, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :isbn %>
    <%= form.text_field :isbn, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :abstract %>
    <%= form.text_area :abstract, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :catalogue %>
    <%= form.text_field :catalogue, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>
<br />
<div class="btn-group" role="group" aria-label="Strumenti">
    <%= link_to 'Visualizza', @book, class: "btn btn-primary" %>
    <%= link_to 'Libri', books_path, class: "btn btn-primary" %>
</div>

app/views/books/index.html.erb
<h1><%= t('mongoid.models.book.other') %></h1>

<%= form_tag '/books', method: :get, class: "form-inline" do %>
  <div class="form-group mx-sm-3 mb-2">
    <%= label_tag :q, "Parola chiave", class: "sr-only"%>
    <%= search_field_tag :q, params[:q], class: "form-control",  placeholder: "Parola chiave" %>
  </div>
  <%= button_tag "Cerca", class: "btn btn-primary mb-2" %>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th><%= t('mongoid.attributes.book.code') %></th>
      <th><%= t('mongoid.attributes.book.title') %></th>
      <th><%= t('mongoid.attributes.book.authors') %></th>
      <th><%= t('mongoid.attributes.book.year') %></th>
      <th><%= t('mongoid.attributes.book.genre') %></th>
      <th><%= t('mongoid.attributes.book.language') %></th>
      <th><%= t('mongoid.attributes.book.spot') %></th>
      <th>ISBN</th>
      <th><%= t('mongoid.attributes.book.catalogue') %></th>
      <th><%= t('helpers.label.status') %></th>
      <th colspan="5" class="text-center"><span class="bi bi-tools"></span></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.code %></td>
        <td><%= book.title %></td>
        <td><%= book.authors.join(", ") %></td>
        <td><%= book.year %></td>
        <td><%= book.genre %></td>
        <td><%= book.language %></td>
        <td><%= book.spot %></td>
        <td><%= book.isbn %></td>
        <td><%= book.catalogue %></td>
        <td>
          <% status = loan_status(book.loans) %>
          <% if status[:loan] %>
            Dal <%= loan_from(status[:returned_date]) %>
          <% else %>
            <span class="bi bi-check-circle"></span>
          <% end %>
        </td>
        <td class="table-<%= status[:css] %>">
          <% if status[:loan] %>
            <%= link_to status[:message], status[:loan] %>
          <% else %>
            <%= link_to status[:message], new_loan_path %>
          <% end %>
        </td>
        <td>
          <%= link_to clone_books_path(params_for_cloning(book)), title: "Clona" do %>
            <span class="bi bi-clipboard-data"></span>
          <% end if current_user %>
        </td>
        <td>
          <%= link_to book, title: "Visualizza" do %>
            <span class="bi bi-view-list"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_book_path(book), title: "Modifica" do %>
            <span class="bi bi-pencil-square"></span>
          <% end if current_user %>
        </td>
        <td>
          <%= link_to book, method: :delete, data: { confirm: 'Sei sicuro?' }, title: "Cancella" do %>
            <span class="bi bi-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @books %>

<div class="btn-group" role="group" aria-label="Strumenti">
  <%= link_to 'Nuovo Libro', new_book_path, class: "btn btn-primary" %>
  <%= link_to 'Home', welcome_path, class: "btn btn-primary" %>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>
<br />
<div class="btn-group" role="group" aria-label="Strumenti">
    <%= link_to 'Libri', books_path, class: "btn btn-primary" %>
</div>

app/views/books/show.html.erb
<p>
  <strong><%= t('mongoid.attributes.book.code') %>:</strong>
  <%= @book.code %>
</p>

<p>
  <strong><%= t('mongoid.attributes.book.title') %>:</strong>
  <%= @book.title %>
</p>

<p>
  <strong><%= t('mongoid.attributes.book.authors') %>:</strong>
  <%= @book.authors.join(", ") %>
</p>

<p>
  <strong><%= t('mongoid.attributes.book.year') %>:</strong>
  <%= @book.year %>
</p>

<p>
  <strong><%= t('mongoid.attributes.book.genre') %>:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong><%= t('mongoid.attributes.book.language') %>:</strong>
  <%= @book.language %>
</p>

<p>
  <strong><%= t('mongoid.attributes.book.spot') %>:</strong>
  <%= @book.spot %>
</p>

<p>
  <strong>ISBN:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong><%= t('mongoid.attributes.book.catalogue') %>:</strong>
  <%= @book.catalogue %>
</p>

<p>
  <strong><%= t('mongoid.attributes.book.abstract') %>:</strong>
  <%= @book.abstract %>
</p>

<% status = loan_status(@book.loans) %>
<% id_name = status[:loan] ? "unloanable-alert" : "loanable" %>
<%= content_tag :p, id: id_name, class: "alert alert-#{status[:css]}" do %>
  <%= link_to_if status[:loan], status[:message], status[:loan] %>.
  <% if status[:loan] %>
    Non prestabile fino al <%= loan_from(status[:returned_date]) %>
  <% end %>
<% end %>

<div class="btn-group" role="group" aria-label="Strumenti">
  <%= link_to 'Presta', new_loan_path("loan[book_id]": @book.id, "book_title": @book.title), class: "btn btn-primary", id: "new-loan" unless status[:loan] || !current_user %>
  <%= link_to 'Clona', clone_books_path(params_for_cloning(@book)), class: "btn btn-primary" if current_user %>
  <%= link_to 'Modifica', edit_book_path(@book), class: "btn btn-primary" if current_user %>
  <%= link_to 'Elenco', books_path, class: "btn btn-primary" %>
</div>

<h2><%= t('mongoid.models.loan.other') %></h2>

<table class="table">
  <thead>
    <tr>
      <th><%= t('mongoid.attributes.loan.date') %></th>
      <th>Data di restituzione</th>
      <th><%= t('mongoid.attributes.loan.place') %></th>
      <th><%= t('mongoid.attributes.loan.reader') %></th>
      <th colspan="3" class="text-center"><span class="bi bi-tools"></span></th>
    </tr>
  </thead>

  <tbody>
  <% loans = @book.loans.order_by(actual_return: :desc, expected_return: :desc).page(params[:page]) %>
    <% loans.each do |loan| %>
      <tr>
        <td><%= l loan.date %></td>
        <td><%= loan.actual_return ? l(loan.actual_return) : l(loan.expected_return) %></td>
        <td><%= loan.place %></td>
        <td><%= loan.reader %></td>
        <td>
          <%= link_to loan, title: "Visualizza" do %>
            <span class="bi bi-view-list"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_loan_path(loan), title: "Modifica" do %>
            <span class="bi bi-pencil-square"></span>
          <% end %>
        </td>
        <td>
          <%= link_to loan, method: :delete, data: { confirm: 'Sei sicuro?' }, title: "Cancella" do %>
            <span class="bi bi-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate loans %>