config/routes.rb
Rails.application.routes.draw do
  resources :sequences, except: [:destroy, :edit, :update]
  resources :settings
  resources :loans
  resources :books do
    get 'clone', on: :collection
  end
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#logout'
  root 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
class Loan
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  field :date, type: Date
  field :expected_return, type: Date
  field :actual_return, type: Date
  field :place, type: String
  field :reader, type: String

  belongs_to :book

  validates_presence_of :date
  validates_presence_of :expected_return
  validates_presence_of :place
  validates_presence_of :reader

  paginates_per 2 if Rails.env.development?

  scope :active, -> (loan_date, return_date) {
    any_of(
      { date: { '$gte' => loan_date, '$lte' => return_date }}, 
      { date: { '$lte' => loan_date }, expected_return: { 'gte' => return_date }, actual_return: nil}, 
      { date: { '$lte' => loan_date }, actual_return: { 'gte' => return_date }},
      { expected_return: { '$gte' => loan_date, '$lte' => return_date }, actual_return: nil },
      { actual_return: { '$gte' => loan_date, '$lte' => return_date }}
    )
    .order_by(actual_return: :desc, expected_return: :desc)
  }
  scope :status, -> (day, quarantine_duration) { 
    any_of(
      { date: { '$lte' => day }, actual_return: nil}, 
      { date: { '$lte' => day }, actual_return: { '$gte' => quarantine_duration.before(day) }},
    )
    .order_by(actual_return: :desc, expected_return: :desc)
  }
  scope :late, -> (day) {
    where(actual_return: nil, expected_return: { '$lte' => day })
  }

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :authorized
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.where(actual_return: nil).order_by([:date, :desc]).page(params[:page])
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
    @loan.book_id = params[:loan][:book_id] if params[:loan] and params[:loan][:book_id]
    today = Date.today
    @loan.date = today
    @loan.expected_return = helpers.day_of_expected_return_in_setting.since today
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)
    if !@loan.valid?
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
      return
    end
    loans = @loan.book.loans.active(@loan.date, helpers.quarantine_duration.since(@loan.expected_return))

    respond_to do |format|
      if loans.count > 0
        flash.now[:notice] = 'Book already lent for this period.'
        format.html { render :new }
        format.json { render json: { message: 'Book already lent for this period.' }, status: :unprocessable_entity }
      elsif @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loan_params
      params.require(:loan).permit(:date, :expected_return, :actual_return, :place, :reader, :book_id)
    end
end

app/helpers/loans_helper.rb
module LoansHelper

    def book_title loan
        if loan && loan.book
            loan.book.title 
        else
            params[:book_title]
        end
    end

    def loan_status(book_loans)
        loan = book_loans.status(loan_date, quarantine_duration).first if book_loans
        if book_loans.nil? || loan.nil?
            message = "Disponibile"
            css="success"
            returned_date = nil
            status = {
                message: message,
                returned_date: returned_date,
                loan: loan,
                css: css
            }
        else
            if loan.actual_return
                returned_date = loan.actual_return
            else
                returned_date = loan.expected_return
            end

            if !loan.actual_return && loan.expected_return <= loan_date
                message = "Ancora da restituire"
                css = "danger"
            else
                if returned_date <= loan_date
                    message = "In quarantena"
                    css="warning"
                else
                    message = "In prestito"
                    css="info"
                end
            end

            status = {
                message: message,
                returned_date: returned_date,
                loan: loan,
                css: css
            }
        end
        logger.debug status
        status
    end

end

app/views/loans/_form.html.erb
<%= form_with(model: loan, local: true) do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
        <% loan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= text_field_tag :autoComplete %>
  <div class="form-group">
    <%= label_tag :book_title, t('helpers.label.book_title')  %>
    <%= text_field_tag :book_title, book_title(loan), class: "form-control", readonly: true %>
    <%= form.hidden_field :book_id %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.date_field :date, class: "form-control col-sm-4 col-md-3" %>
  </div>

  <div class="form-group">
    <%= form.label :expected_return %>
    <%= form.date_field :expected_return, class: "form-control col-sm-4 col-md-3" %>
  </div>

  <% if !current_page?(controller: :loans, action: :new) %>
  <div class="form-group">
    <%= form.label :actual_return %>
    <%= form.date_field :actual_return, class: "form-control col-sm-4 col-md-3" %>
  </div>
  <% end %>

  <div class="form-group">
    <%= form.label :place %>
    <%= form.text_field :place, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :reader %>
    <%= form.text_field :reader, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

<%= javascript_pack_tag 'autocomplete' %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<br />
<div class="btn-group" role="group" aria-label="Strumenti">
    <%= link_to 'Visualizza', @loan, class: "btn btn-primary" %>
    <%= link_to 'Prestiti', loans_path, class: "btn btn-primary" %>
</div>

app/views/loans/index.html.erb
<h1><%= t('mongoid.models.loan.other') %></h1>

<table class="table">
  <thead>
    <tr>
      <th><%= t('helpers.label.book_title') %></th>
      <th><%= t('mongoid.attributes.loan.date') %></th>
      <th><%= t('mongoid.attributes.loan.expected_return') %></th>
      <th><%= t('mongoid.attributes.loan.place') %></th>
      <th><%= t('mongoid.attributes.loan.reader') %></th>
      <th colspan="3" class="text-center"><span class="bi bi-tools"></span></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><%= link_to loan.book.title, loan.book %></td>
        <td><%= l loan.date %></td>
        <td><%= l loan.expected_return %></td>
        <td><%= loan.place %></td>
        <td><%= loan.reader %></td>
        <td>
          <%= link_to loan, title: "Visualizza" do %>
            <span class="bi bi-view-list"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_loan_path(loan), title: "Modifica" do %>
            <span class="bi bi-pencil-square"></span>
          <% end %>
        </td>
        <td>
          <%= link_to loan, method: :delete, data: { confirm: 'Sei sicuro?' }, title: "Cancella" do %>
            <span class="bi bi-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @loans %>

<div class="btn-group" role="group" aria-label="Strumenti">
  <%= link_to 'Nuovo Prestito', new_loan_path, class: "btn btn-primary" %>
  <%= link_to 'Home', welcome_path, class: "btn btn-primary" %>
</div>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>
<br />
<div class="btn-group" role="group" aria-label="Strumenti">
    <%= link_to 'Prestiti', loans_path, class: "btn btn-primary" %>
</div>

app/views/loans/show.html.erb
<p>
  <strong><%= t('helpers.label.book_title') %>:</strong>
  <%= link_to @loan.book.title, @loan.book %>
</p>

<p>
  <strong><%= t('mongoid.attributes.loan.date') %>:</strong>
  <%= l @loan.date %>
</p>

<p>
  <strong><%= t('mongoid.attributes.loan.expected_return') %>:</strong>
  <%= l @loan.expected_return %>
</p>

<% if @loan.actual_return %>
<p>
  <strong><%= t('mongoid.attributes.loan.actual_return') %>:</strong>
  <%= l @loan.actual_return %>
</p>
<% end %>

<p>
  <% if @loan.actual_return %>
    <strong>Data di fine quarantena:</strong>
    <%= loan_from(@loan.actual_return) %>
  <% else %>
    <strong>Data prevista di fine quarantena:</strong>
    <%= loan_from(@loan.expected_return) %>
  <% end %>
</p>


<p>
  <strong><%= t('mongoid.attributes.loan.place') %>:</strong>
  <%= @loan.place %>
</p>

<p>
  <strong><%= t('mongoid.attributes.loan.reader') %>:</strong>
  <%= @loan.reader %>
</p>

<div class="btn-group" role="group" aria-label="Strumenti">
  <%= link_to 'Modifica', edit_loan_path(@loan), class: "btn btn-primary" %>
  <%= link_to 'Elenco', loans_path, class: "btn btn-primary" %>
</div>